---
- hosts: all

  become: true
  tasks:
  - name: 'apt: update & upgrade'
    apt:
      upgrade: yes
      update_cache: yes
      autoremove: yes
    register: apt
  - debug: msg={{ apt.stdout.split('\n')[:-1] }}